---
abstract: 'convert ajax uri to crawlable'
author:
  - 'mala <cpan@ma.la>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: URI-CrawlableHash
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Filter::Util::Call: 0
  Guard: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mala/p5-URI-CrawlableHash.git
version: 0.02
